website:landing:
  - changed-files:
    - any-glob-to-any-file: "landing/**"

website:blog:
  - changed-files:
    - any-glob-to-any-file: "blog/**"

website:islam:
  - changed-files:
    - any-glob-to-any-file: "islam/**"
